import type { Metadata } from "next";
import { Nunito_Sans} from "next/font/google";
import { Navigation } from "@/components/Navigation/Navigation";
import { CountryStoreProvider } from "@/providers/CountryStoreProvider";
import { QueryProvider } from "@/providers/QueryProvider";

import "./globals.css";

const nunitoSans = Nunito_Sans({
  subsets: ["latin"],
  variable: "--font-nunito-sans",
})

export const metadata: Metadata = {
  title: "REST Countries",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark scroll-smooth">
      <body className={`${nunitoSans.variable} max-w-full min-h-screen font-global bg-very-light-gray dark:bg-very-dark-blue text-very-dark-blue-light-mode dark:text-white`}>
        <CountryStoreProvider>
          <QueryProvider>
            <Navigation />
            {children}
          </QueryProvider>
        </CountryStoreProvider>
      </body>
    </html>
  )
}
