import type { Metadata } from "next";
import { Nunito_Sans} from "next/font/google";
import { Navigation } from "@/components/Navigation/Navigation";
import "./globals.css";

const nunitoSans = Nunito_Sans({
  subsets: ["latin"],
  variable: "--font-nunito-sans",
})

export const metadata: Metadata = {
  title: "REST Countries",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunitoSans.variable} max-w-full min-h-screen font-global bg-very-light-gray`}>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
